#!/usr/bin/env node
// Generate TypeScript types from the FastAPI OpenAPI spec.
//
// Source-of-truth order:
//   1) live API at $NEXT_PUBLIC_API_URL/openapi.json (preferred — always
//      reflects the running backend)
//   2) ../tmp/openapi.json on disk (used in CI / offline builds; produced
//      by `python -m lapua_rag.cli openapi-dump`)
//
// Output: lib/api/openapi.d.ts
//
// Run with: npm run gen-types

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../..");
const offlinePath = resolve(repoRoot, "tmp/openapi.json");
const outPath = resolve(here, "../lib/api/openapi.d.ts");
const apiBase = (process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080").replace(/\/$/, "");
const liveUrl = `${apiBase}/openapi.json`;

async function loadSpec() {
  try {
    const r = await fetch(liveUrl, { signal: AbortSignal.timeout(2_000) });
    if (r.ok) {
      console.log(`[gen-types] using live spec at ${liveUrl}`);
      return await r.json();
    }
    console.warn(`[gen-types] ${liveUrl} returned ${r.status}, falling back to offline`);
  } catch (err) {
    console.warn(`[gen-types] live fetch failed (${err.message}), falling back to offline`);
  }
  if (!existsSync(offlinePath)) {
    throw new Error(
      `[gen-types] no OpenAPI spec available. Either start the backend ` +
        `(lapua-rag serve) or write one to ${offlinePath} via \n` +
        `  python -c "import json,pathlib; from lapua_rag.api.app import create_app; ` +
        `pathlib.Path('tmp/openapi.json').write_text(json.dumps(create_app().openapi()))"`,
    );
  }
  console.log(`[gen-types] using offline spec at ${offlinePath}`);
  return JSON.parse(await readFile(offlinePath, "utf8"));
}

const spec = await loadSpec();
const ast = await openapiTS(spec, { exportType: true });
const tsSource = `// Auto-generated by scripts/gen-types.mjs. Do not edit by hand.\n${astToString(ast)}`;

await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, tsSource, "utf8");
console.log(`[gen-types] wrote ${outPath}`);
